site_name: Dubbo
nav:
  - "用户手册":
      - "入门":
          - "背景": 'user/preface/background.md'
          - "需求": 'user/preface/background.md'
          - "架构": 'user/preface/architecture.md'
          - "用法": 'user/preface/usage.md'
      - "快速启动": 'user/quick-start.md'
      - "依赖": 'user/dependencies.md'
      - "成熟度": 'user/maturity.md'
      - "配置":
        - "XML 配置": 'user/configuration/xml.md'
        - "API 配置": 'user/configuration/api.md'
        - "Annotation 配置": 'user/configuration/annotation.md'
        - "动态配置中心": 'user/configuration/annotation.md'
        - "配置加载流程": 'user/configuration/configuration-load-process.md'
        - "自动加载环境变量": 'user/configuration/environment-variables.md'
      - "示例":
        - "启动时检查": 'user/demos/preflight-check.md'
        - "集群容错": 'user/demos/fault-tolerent-strategy.md'
        - "负载均衡": 'user/demos/loadbalance.md'
        - "线程模型": 'user/demos/thread-model.md'
        - "直连提供者": 'user/demos/explicit-target.md'
        - "只订阅": 'user/demos/subscribe-only.md'
        - "只注册": 'user/demos/registry-only.md'
        - "静态服务": 'user/demos/static-service.md'
        - "多协议": 'user/demos/multi-protocols.md'
        - "多注册中心": 'user/demos/multi-registry.md'
        - "服务分组": 'user/demos/service-group.md'
        - "多版本": 'user/demos/multi-versions.md'
        - "分组聚合": 'user/demos/group-merger.md'
        - "参数验证": 'user/demos/parameter-validation.md'
        - "结果缓存": 'user/demos/result-cache.md'
        - "泛化引用": 'user/demos/generic-reference.md'
        - "泛化实现": 'user/demos/generic-service.md'
        - "回声测试": 'user/demos/echo-service.md'
        - "上下文信息": 'user/demos/context.md'
        - "隐式参数": 'user/demos/attachment.md'
        - "异步调用": 'user/demos/async-call.md'
        - "服务端异步": 'user/demos/async-execute-on-provider.md'
        - "本地调用": 'user/demos/local-call.md'
        - "参数回调": 'user/demos/callback-parameter.md'
        - "事件通知": 'user/demos/events-notify.md'
        - "本地存根": 'user/demos/local-stub.md'
        - "本地伪装": 'user/demos/local-mock.md'
        - "延迟暴露": 'user/demos/delay-publish.md'
        - "并发控制": 'user/demos/concurrency-control.md'
        - "连接控制": 'user/demos/config-connection.md'
        - "延迟连接": 'user/demos/lazy-connect.md'
        - "粘滞连接": 'user/demos/stickiness.md'
        - "令牌验证": 'user/demos/token-authorization.md'
        - "路由规则": 'user/demos/routing-rule.md'
        - "配置规则": 'user/demos/config-rule.md'
        - "服务降级": 'user/demos/service-downgrade.md'
        - "优雅停机": 'user/demos/graceful-shutdown.md'
        - "主机绑定": 'user/demos/hostname-binding.md'
        - "日志适配": 'user/demos/logger-strategy.md'
        - "访问日志": 'user/demos/accesslog.md'
        - "服务容器": 'user/demos/service-container.md'
        - "Reference Config 缓存": 'user/demos/reference-config-cache.md'
#
#    * [6.43 分布式事务](./demos/distributed-transaction.md)
#    * [6.44 线程栈自动dump](./demos/dump.md)
#    * [6.45 Netty4](./demos/netty4.md)
#    * [6.46 Kryo和FST序列化](./demos/serialization.md)
#    * [6.47 简化注册中心URL](./demos/simplify-registry-data.md)
#    * [7 API 参考手册](./references/api.md)
#    * [8 schema 配置参考手册](./references/xml/introduction.md)
#    * [8.1 dubbo:service](./references/xml/dubbo-service.md)
#    * [8.2 dubbo:reference](./references/xml/dubbo-reference.md)
#    * [8.3 dubbo:protocol](./references/xml/dubbo-protocol.md)
#    * [8.4 dubbo:registry](./references/xml/dubbo-registry.md)
#    * [8.5 dubbo:monitor](./references/xml/dubbo-monitor.md)
#    * [8.6 dubbo:application](./references/xml/dubbo-application.md)
#    * [8.7 dubbo:module](./references/xml/dubbo-module.md)
#    * [8.8 dubbo:provider](./references/xml/dubbo-provider.md)
#    * [8.9 dubbo:consumer](./references/xml/dubbo-consumer.md)
#    * [8.10 dubbo:method](./references/xml/dubbo-method.md)
#    * [8.11 dubbo:argument](./references/xml/dubbo-argument.md)
#    * [8.12 dubbo:parameter](./references/xml/dubbo-parameter.md)
#    * [8.13 dubbo:config-center](./references/xml/dubbo-config-center.md)
#    * [9 协议参考手册](./references/protocol/introduction.md)
#    * [9.1 dubbo://](./references/protocol/dubbo.md)
#    * [9.2 rmi//](./references/protocol/rmi.md)
#    * [9.3 hessian://](./references/protocol/hessian.md)
#    * [9.4 http://](./references/protocol/http.md)
#    * [9.5 webservice://](./references/protocol/webservice.md)
#    * [9.6 thrift://](./references/protocol/thrift.md)
#    * [9.7 memcached://](./references/protocol/memcached.md)
#    * [9.8 redis://](./references/protocol/redis.md)
#    * [9.9 rest://](./references/protocol/rest.md)
#    * [10 注册中心参考手册](./references/registry/introduction.md)
#    * [10.1 Multicast 注册中心](./references/registry/multicast.md)
#    * [10.2 Zookeeper 注册中心](./references/registry/zookeeper.md)
#    * [10.3 Redis 注册中心](./references/registry/redis.md)
#    * [10.4 Simple 注册中心](./references/registry/simple.md)
#    * [11 元数据中心参考手册](./references/metadata/introduction.md)
#    * [11.1 Redis](./references/metadata/metadata-redis.md)
#    * [11.2 Zookeeper](./references/metadata/metadata-zookeeper.md)
#    * [12 telnet 命令参考手册](./references/telnet.md)
#    * [13 在线运维命令-QOS](./references/qos.md)
#    * [14 maven 插件参考手册](./references/maven.md)
#    * [15 服务化最佳实践](./best-practice.md)
#    * [16 推荐用法](./recommend.md)
#    * [17 容量规划](./capacity-plan.md)
#    * [18 性能测试报告](./perf-test.md)
#    * [19 测试覆盖率报告](./coveragence.md)
#    * [20 版本与升级](./versions/index.md)
#    * [20.1 2.7.x升级步骤及注意事项](./version-270.md)
#

theme: readthedocs